### ISSUE TITLE
Import lantz issue pyqt

### ISSUE THREAD

**Issue by kayfor2** [LabPy/lantz#80]
I use Anaconda 3.6 64 bit on windows, and I get the following error when I try to import lantz. Can you please help?

import lantz
Traceback (most recent call last):

  File "<ipython-input-6-33ae188bba0f>", line 1, in <module>
    import lantz

  File "C:\ProgramData\Anaconda3\lib\site-packages\lantz\__init__.py", line 25, in <module>
    from .driver import Driver, Feat, DictFeat, Action, initialize_many, finalize_many

  File "C:\ProgramData\Anaconda3\lib\site-packages\lantz\driver.py", line 19, in <module>
    from .utils.qt import MetaQObject, SuperQObject, QtCore

  File "C:\ProgramData\Anaconda3\lib\site-packages\lantz\utils\qt.py", line 27, in <module>
    (QT_API, QT_API_PYSIDE, QT_API_PYQT, QT_MOCK))

RuntimeError: Invalid Qt API 'pyqt5', valid values are: 'pyside', 'pyqt', 'mock'

**Comment by vascotenner** [comment]
The current master branch does only support Qt4. It look like you have installed Qt5. 

See also #79
